version: 2.1
jobs:
  java-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: 编译主代码
          command: |
            mkdir -p out
            find wfj-utils/src -name "*.java" > sources.txt
            javac -d out @sources.txt
      - run:
          name: 编译测试代码
          command: |
            mkdir -p test-out
            wget -q https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
            find wfj-utils/test -name "*.java" > test_sources.txt
            javac -cp out:junit-platform-console-standalone-1.9.3.jar -d test-out @test_sources.txt
      - run:
          name: 运行单元测试
          command: |
            java -jar junit-platform-console-standalone-1.9.3.jar --class-path out:test-out --scan-class-path
workflows:
  java-test-workflow:
    jobs:
      - java-test
