version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  maven-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Restore Maven cache
          command: |
            mkdir -p ~/.m2
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-
      - run:
          name: Run Unit Tests
          command: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - maven-test:
          requires:
            - say-hello
